{
 "title": "Apache Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(apache_accesses_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Traffic in kB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total[1m])",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Response Time in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(apache_duration_ms_total{}[1m])) / sum(rate(apache_accesses_total{}[1m]))",
     "legendFormat": "Times"
    }
   ]
  },
  {
   "title": "Load(1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "apache_load{interval=\"1min\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Load(5min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "apache_load{interval=\"5min\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Apache Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_info", "legendFormat": "{{version}}" }
   ]
  }
 ]
}